### ISSUE TITLE
Corrupt file generated using write() method in Windows 

### ISSUE THREAD

**Issue by pebreo** [brianray/mm#18]
The `write()` method generates a corrupt file that MS Excel (running in Windows environment) cannot read. 

When opening the file Excel gives the following error:

`"Excel found unreadable content in 'myfile.xls'. Do you want to recover the contents of this workbook?"`

Given the following code:

```
my_data = [
            {
                'msg': "My first Cell",
                'id': 1,
                'when': 'now',
            },
            {
                'msg': "My second Cell",
                'id': 2,
                'when': 'now',
            },
]

mm_doc = mm.Document(my_data)
mm_doc.write("myfile.xls") # generates a corrupt file
```

**Comment by brianray** [comment]
Great, Paul. Add a unit test to display this fix and I will accept your pull request.
