### ISSUE TITLE
Doing more with less

### ISSUE THREAD

**Issue by gamesbook** [brianray/mm#2]
Brian; would really love to use this.  I had been "rolling my own" Excel output for a Django project before coming across your project.  I had been wondering how to incorporate decent formatting to the data and your project seems perfect for that.

One small (?) issue though.  The bulk of data I output from my views is in the form of (a) a list of headers and (b) a "list of lists" for data.  This format is perfect for easy conversion to HTML tables, CSV data or Excel files.  However your examples are dictionary-based and include header names encapsulated in each "row".  Do you see a way to upgrade your project to handle the kind of input I would like to have?  Thanks!

**Comment by brianray** [comment]
Thanks for your question.

Concerning using a two lists, that should not be a problem and I had originally designed this scenario. I will work up a test example later and fix if it is not working.

Meanwhile, did you realize there is a pure Django example. It works something like this:

``` python

from yourproject.models import TestModel
from mm.contrib.django.data_model import DjangoDataModel
from mm.contrib.django.grid import DjangoGrid

django_query_set = TestModel.objects.all()
mm_doc = mm.Document(django_query_set, 
              data_model_class=DjangoDataModel, 
              grid_class=DjangoGrid)
mm_doc.write("django_example.xls")

```

**Comment by gamesbook** [comment]
Yes, I saw the Django example.  But most of my outputs are not simple django_query_sets - they have had to go through lot of processing before emerging as lists!

**Comment by brianray** [comment]
Ok, I pushed this feature.  also added a test for this here:

 https://github.com/brianray/mm/blob/master/tests/basic_tests.py#L38

That should give you a good idea on how to do this. You will need to set the order argument on Document. If it works, please Close this case. Thanks!

**Comment by gamesbook** [comment]
Brian.  My apologies.  The client for the project I am working on reassigns me to "other priorities" if progress is slow in any area.  I _will_ be using this, but cannot test it right away.  I will close this and rather open a new issue if I have problems at that time.
