### ISSUE TITLE
pip install error

### ISSUE THREAD

**Issue by tetter36** [brianray/mm#28]
When I tried to install Marmir with pip it failed.  Attached is a screenshot of the error log I received.  Note, I haven't had any issues downloading anything else with pip. I also used pip to install another package right after I tried to install this one, and I didn't have any issues.

![error_log](https://cloud.githubusercontent.com/assets/5679760/3848825/730601cc-1e73-11e4-9ef5-2219fc77a66a.jpg)

**Comment by breisfeld** [comment]
It appears that mm, as of 65744d46a134f72444b5a5962fb81a91ace459bd, is not compatible with python 3 `import` semantics.
