### ISSUE TITLE
No Loggers for ... 

### ISSUE THREAD

**Issue by brianray** [brianray/mm#3]
users reported getting these messages about "no loggers"

**Comment by tathagata** [comment]
I'm using Python 2.7  on Windows 7, with Visual Studio 2012. [Haven't tested on GNU/Linux or OS X]
The error message I'm getting is 

```
No handlers could be found for logger "mm.composer_xls"
```

According to a [SO thread](http://stackoverflow.com/questions/345991/python-no-handlers-could-be-found-for-logger-opengl-error) its due log config settings 

The error goes away if I add 

```
 import logging
 logging.basicConfig()
```

but generates the following warnings. (looks harmless and unrelated)

```
WARNING:mm.composer_xls:Unknown text_align None
```

The spreadsheet still remains corrupt and generates the following log message 

```
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<recoveryLog xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main">     <logFileName>error088520_01.xml</logFileName><summary>Errors were detected in file 'C:\Users\Tathagata\Documents\visual studio 2012\Projects\PythonApplication4\PythonApplication4\example1.xls'</summary><additionalInfo><info>Excel recovered your formulas and cell values, but some data may have been lost.</info></additionalInfo></recoveryLog>
```

**Comment by brianray** [comment]
Thanks for fixing the logs, can you make a pull request. Concerning the spreadsheet, do the examples work? Can you attach?

**Comment by tathagata** [comment]
https://dl.dropbox.com/u/18146922/example.xls

is what is generated with the first example on the README (http://pastebin.com/zdr6k3Jy).

Curious if there's a way to inspect an xls to understand what's wrong with it - other than opening it up on excel.
